GET http://localhost:5266/games/
###
GET http://localhost:5266/games/1

###
POST http://localhost:5266/games
Content-Type: application/json

 {
 
    "name":"Mine Craft",
    "genre":"Kids an Family",
    "price":19.9,
    "releaseDate":"2011-11-15"

 }